FROM nvidia/cuda:11.7.1-base-ubuntu22.04
# FROM nvidia/cuda:11.7.1-runtime-ubuntu20.04
# FROM pytorch/manylinux-cuda118:latest

# nvidia-smi

# https://zhuanlan.zhihu.com/p/471484611

# https://blog.csdn.net/qq_40541102/article/details/127792339

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     bzip2 \
#     g++ \
#     git \
#     vim \
#     python-dev \
#     python3-pip \
#     build-essential \
#     wget && \
#     rm -rf /var/lib/apt/lists/*

# RUN apt-get update && \
#     DEBIAN_FRONTEND=noninteractive apt-get install -y — no-install-recommends python3-pip python3-dev wget \
#     bzip2 libopenblas-dev pbzip2 libgl1-mesa-glx && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# Install miniconda
# COPY Miniconda3-latest-Linux-x86_64.sh /temp/
# RUN chmod +x /temp/Miniconda3-latest-Linux-x86_64.sh
# RUN sh Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda
# RUN rm Miniconda3-latest-Linux-x86_64.sh